[package]
name = "homeautomation-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
random-string = "1.1.0"
